language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/carolineorlando/blogspotter.git
  - REPO_TARGET_BRANCH: gh-pages
  - secure: bZJkhzzjjJfWzwb7QRRY4L0hCG7Ax2I5XdgXpfLBjh2M1mOYoT5L3+onFNCbO9/wDVdJgmuZM3JEMY7sy2fLzULOF1teviDkYGH7smiWQZHRBdpz4ZUkSoOPQuIjfHUiWtEHBCpQ5IxNoKnc3uQtC608qMfL7Y6a9Bww7929kGKSgEN4DyMNOOrpfVy/4348LpLNeFRvg5aZfKoyWRjfF0bLElqogpkk4eyip/3oCeSmm+hIBXdK6ZtZme9T/5ElznT3T07krQy9X04RhYdhY4emClt+4t7grBMOiTlfcZamFsx2xM5Y8VrExLR7hGveelQoKuJVppBrLY+aH+e7ApF79aFEOZKefF4IcAO47ThBQ+O6p1SpYqat9lnFHxQPhdonJBwERnLsnXPujBCwpHyJJnRB9qEyRg+L0E7bxtohcR4CvpJk80fGx2AxcIljSKHOMC745SGjr97azfC0yEsOs5wS/yXA/Thyg62Ssms3nUfQTYkI4Pi630pyjB5ID9gadD+gJJgvrlKqRuEbzf0iAqz1OFsLzDuXC2e5hmFJ2RWAYItOmUdnNViB6oxzVBFQC/l/U6aD0udtVYoNftxI84/GnoS0vdB/GWh9H8C5jRywXezhiYbZXscfmVBCsqQ5WDUXhgXX7shw+NOZGVwrB1kiy1MnbkPRJfpsy+c=
  - secure: PlCUpz0uJUb22NWUFZlN2elgFP0SuMrDEwv+/YOb5cwCvZ4oHLEsHAABGdzgIltfoyg0oMXmFjWGNFOUK3bD7Qn92rWhoKLsJ0nf8C+e4z9NDan728LPnlMWxvgwQ6X71bXDAxpXLnVFpjUMj/AEJ09ILxzrVyjzg3scbmMvEItffn2WPLzk7zD9MIhIogRkDECleo48WQxkT32B5S1RjOs9nnhzhYil69XAAGpdJihLke7HRNlVVUisKBRKuvzjKlAjg9U91Z+Z9/zKFlPKck7Ukig0iDCtmp4dLzQaSF9NQzgWpNyR6tK2fVM/1jM+iNYn/BhHpnKyFYrsRBR2jNKYBj6t4j76l+0HNUBV718kRxGRHk8rfrekGRclhqqKhv3/U/Ry4Oj17xyjN1++x7qKlPcBaFUnKH30yhI7BAvWt0M/eaaAYheKLW6p8Pcfu42+f39y7lpGU8Z4HUGujRPrn9knyFmrutscccDSxt+WzEyvh49rYE+8emTH5oowpo78wZOowdBy0k1Y5qr9IRa7oif5DWKUcd+IokbBTa3ZCyu1UO8WAMGdkPt/5jCIbCKEgzlIP49z2hAxFFsduQA603i+ZCR77BUoJ5pdkcPkzi/kDOVooOlYpoIV4twZZ4WurvhFFww+tEDXK0TCgi0vpD3Iwba36Z+ZsSr5iG4=
# whitelist
branches:
  only:
    - master