# Site settings
title: Blogspotter
email: info@blogspotter.co
description: A collection of conversations with the style influencers of the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:title/

copyright: Copyright 2016 Glitter Groupe Media & Blogspotter. All rights reserved.

paginate: 10
paginate_path: "/page:num/"
encoding: UTF-8

gems: [jekyll-paginate]
