title: Blogspotter
email: info@blogspotter.co
description: A collection of conversations with the style influencers of the web.
url: "http://blogspotter.co"
markdown: kramdown
permalink: /:title/
copyright: Copyright 2013-2017 Glitter Groupe Media & Blogspotter. All rights reserved.
encoding: UTF-8
exclude:
  - node_modules
  - package.json
  - gulpfile.js
  - src
  - Gemfile
  - CNAME
  - README.md
include:
  - _pages
gems:
  - jekyll-sitemap
  - jekyll-redirect-from